In [15]:
#IMPORT LIBRARIES and packages
import numpy as np
import pandas as pd
from pydataset import data
from sklearn import svm
from sklearn import model_selection
from statsmodels.tools.eval_measures import mse

# LOAD DATASET - provided by task 2 team leader Sulaiman Mutawalli
df = pd.read_excel(r'/Users/dorsa/data/linear.xlsx')

In [16]:
# DATA PREPARATION
df.dropna()
df.head()

   year  population   gdp  steel       coal       oil        gas       co2
0  1950    2.499322  0.89  189.0  11332.575  6055.578  2136.6338  6.003272
1  1951    2.543130  0.94  205.0  11939.019  6867.236  2534.5093  6.379796
2  1952    2.590271  0.99  221.0  11870.501  7218.299  2729.6267  6.465727
3  1953    2.640279  1.04  237.0  11923.186  7632.513  2886.3450  6.647763
4  1954    2.691979  1.09  253.0  11769.438  7990.694  3027.5981  6.789969

In [11]:
x = df.drop(['co2'], axis=1).values
y = df['co2'].values

In [18]:
# SCALING OF VARIABLES

df = (df - df.min()) / (df.max() - df.min())
df.head()

,year,population,gdp,steel,coal,oil,gas,co2
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.014085,0.008098,0.000523,0.009081,0.017526,0.017593,0.010362,0.012099
2,0.028169,0.016811,0.001046,0.018161,0.015546,0.025203,0.015444,0.014860
3,0.042254,0.026055,0.001569,0.027242,0.017068,0.034181,0.019525,0.020709
4,0.056338,0.035611,0.002092,0.036322,0.012625,0.041945,0.023204,0.025279

In [22]:
# MODEL DEVELOPMENT

# Independent and dependent variables
X = df[['year', 'population', 'gdp', 'steel', 'coal',
        'oil', 'gas']]
y = df['co2']


# Train and test sets
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3, random_state=1)

# Create instance of model
h1 = svm.SVR()

In [23]:
h1.fit(X_train, y_train)

SVR()

In [25]:
# Model Evaluation

y_pred = h1.predict(X_test)
print(mse(y_pred, y_test))

0.004799126214121039